In [1]:
import tensorflow as tf
t1 = tf.constant([0, 1, 2, 3, 4, 5, 6, 7])
t1

<tf.Tensor: shape=(8,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7], dtype=int32)>

In [2]:
s1 = tf.slice(t1, begin=[1], size=[3])
print(s1)  # Output: [1 2 3]

tf.Tensor([1 2 3], shape=(3,), dtype=int32)


In [4]:
# Pythonic Slicing:/

s1 = t1[1:4]  # Same output as above
print(s1)

tf.Tensor([1 2 3], shape=(3,), dtype=int32)


In [6]:
t2 = tf.constant([[0, 1, 2],
                  [3, 4, 5],
                  [6, 7, 8]])
print(t2)

tf.Tensor(
[[0 1 2]
 [3 4 5]
 [6 7 8]], shape=(3, 3), dtype=int32)


In [7]:
# Get the first row
first_row = tf.slice(t2, [0, 0], [1, tf.shape(t2)[1]])
print('First Row:\n', first_row)

# Get the second column
second_column = tf.slice(t2, [0, 1], [tf.shape(t2)[0], 1])
print('\nSecond Column:\n', second_column)

# Get the second and third columns
second_third_columns = tf.slice(t2, [0, 1], [tf.shape(t2)[0], 2])
print('\nSecond & Third Columns:\n', second_third_columns)

First Row:
 tf.Tensor([[0 1 2]], shape=(1, 3), dtype=int32)

Second Column:
 tf.Tensor(
[[1]
 [4]
 [7]], shape=(3, 1), dtype=int32)

Second & Third Columns:
 tf.Tensor(
[[1 2]
 [4 5]
 [7 8]], shape=(3, 2), dtype=int32)


In [12]:
# 2. Extracting tensors

# advance picking

t3 = tf.constant([[[1, 3, 5, 7],
                   [9, 11, 13, 15]],
                  [[17, 19, 21, 23],
                   [25, 27, 29, 31]]])
print(t3)


Indices = [[0, 0, 0], [1, 1, 1], [1, 0, 3]]
special_picks = tf.gather_nd(t3, indices=Indices, batch_dims=0)
print(special_picks)

print('The value at index t3[0, 0, 0] :',t3[Indices[0]])
print('The value at index t3[1, 1, 1] :',t3[Indices[1]])
print('The value at index t3[1, 0, 3] :',t3[Indices[2]])

tf.Tensor(
[[[ 1  3  5  7]
  [ 9 11 13 15]]

 [[17 19 21 23]
  [25 27 29 31]]], shape=(2, 2, 4), dtype=int32)
tf.Tensor([ 1 27 23], shape=(3,), dtype=int32)
The value at index t3[0, 0, 0] : tf.Tensor(1, shape=(), dtype=int32)
The value at index t3[1, 1, 1] : tf.Tensor(27, shape=(), dtype=int32)
The value at index t3[1, 0, 3] : tf.Tensor(23, shape=(), dtype=int32)


In [15]:
# inserting tensor

# Meet tf.scatter_nd:
import tensorflow as tf
t4 = tf.zeros_like(tf.constant([0, 0, 0, 0, 0, 0, 0, 0]))
print(t4)

Index = [[1], [2], [3], [6]]
values = [10, 20, 25, 30]
t4 = tf.scatter_nd(indices=Index, 
                   updates=values, 
                   shape=[8])
print(t4)  # Output: [0 10 20 25 0 0 30 0]

tf.Tensor([0 0 0 0 0 0 0 0], shape=(8,), dtype=int32)
tf.Tensor([ 0 10 20 25  0  0 30  0], shape=(8,), dtype=int32)


In [17]:
# Beyond Flat Land:
t5 = tf.zeros(shape=(4, 5))
print(t5)


Index = [[0, 0], 
         [1, 1], 
         [2, 2]]
values = [100, 200, 300]
t5 = tf.scatter_nd(indices=Index, 
                   updates=values, 
                   shape=t5.shape)
print(t5)  # Output: [[100 0 0 0 0], [0 200 0 0 0], [0 0 300 0 0], [0 0 0 0 0]]

tf.Tensor(
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]], shape=(4, 5), dtype=float32)
tf.Tensor(
[[100   0   0   0   0]
 [  0 200   0   0   0]
 [  0   0 300   0   0]
 [  0   0   0   0   0]], shape=(4, 5), dtype=int32)
