# 1. Initializing Tensors
# Creating a Basic Tensor

In [1]:
import torch

In [2]:
# Creating a 2x3 tensor
my_tensor = torch.tensor([[1, 2, 3], [4, 5, 6]], dtype=torch.float32)
print(my_tensor)

tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [3]:
print(f"Data Type: {my_tensor.dtype}")
print(f"Device: {my_tensor.device}")
print(f"Shape: {my_tensor.shape}")
print(f"Requires Gradient: {my_tensor.requires_grad}")

Data Type: torch.float32
Device: cpu
Shape: torch.Size([2, 3])
Requires Gradient: False


In [5]:
x_empty = torch.empty(3, 3)        # Uninitialized 3x3 tensor
x_zeros = torch.zeros(3, 3)       # 3x3 tensor filled with zeros
x_random = torch.rand(3, 3)       # Random values in [0, 1)
x_identity = torch.eye(3)         # 3x3 identity matrix


print(x_empty)
print(x_zeros)
print(x_random)
print(x_identity)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([[0.2726, 0.4348, 0.8536],
        [0.4494, 0.2627, 0.9172],
        [0.2147, 0.4503, 0.3313]])
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


# 2. Tensor Mathematical Operations
# Basic Arithmetic Operations
# PyTorch allows simple operations like addition, subtraction, multiplication, and division:

In [6]:
x = torch.tensor([1, 2, 3])
y = torch.tensor([4, 5, 6])

In [9]:
z_add = x + y          # Element-wise addition
z_sub = x - y          # Element-wise subtraction
z_mul = x * y          # Element-wise multiplication
z_div = x / y          # Element-wise division

print(f" Addition: {z_add}")
print(f" Subtraction: {z_sub}")
print(f" Multiplication: {z_mul}")
print(f" Division: {z_div}")

 Addition: tensor([5, 7, 9])
 Subtraction: tensor([-3, -3, -3])
 Multiplication: tensor([ 4, 10, 18])
 Division: tensor([0.2500, 0.4000, 0.5000])


In [10]:
# matrix multiplication
# For matrix operations, use torch.mm or the @ operator:

x1 = torch.rand(2, 3)
x2 = torch.rand(3, 2)

In [13]:
# Matrix multiplication
result1 = torch.mm(x1, x2)
# Equivalent:
result2 = x1 @ x2

print(result1)
print(result2)

tensor([[0.6124, 0.9956],
        [0.5891, 0.9284]])
tensor([[0.6124, 0.9956],
        [0.5891, 0.9284]])


In [19]:
# In-Place Operations
# Use operations ending with _ (like add_) to modify a tensor in-place:

x = torch.tensor([1, 2, 3])
x.add_(1)  # Adds 1 to each element of x
print(x)   # tensor([2, 3, 4])


tensor([2, 3, 4])


In [20]:
x.add_(2)
print(x)

tensor([4, 5, 6])


# 3. Tensor Indexing
# Accessing Elements
<!-- Tensors can be indexed like lists or NumPy arrays: -->

In [21]:
x = torch.tensor([[1, 2, 3], [4, 5, 6]])

In [23]:
# Access specific elements
print(x[0, 0])  # First element (1)
print(x[:, 1])  # Second column ([2, 5])
print(x[1, :])  # Second row ([4, 5, 6])
print(x[1, 2])  # Last element (6)

tensor(1)
tensor([2, 5])
tensor([4, 5, 6])
tensor(6)


In [25]:
# Advanced Indexing
# Use conditions or fancy indexing for more control:

x = torch.arange(10)
print(x)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [31]:
# Elements less than 5
print(x[x < 5])  # tensor([0, 1, 2, 3, 4])
# Even numbers
print(x[x % 2 == 0])  # tensor([0, 2, 4, 6, 8])
# Element greater than 5
print(x[x >= 5])
# Multiples of 4
print(x[x % 4 == 0])
# Odd numbers
print(x[x % 2 != 0])

tensor([0, 1, 2, 3, 4])
tensor([0, 2, 4, 6, 8])
tensor([5, 6, 7, 8, 9])
tensor([0, 4, 8])
tensor([1, 3, 5, 7, 9])


# 4. Tensor Reshaping
# Changing Tensor Shape
<!-- Use view() or reshape() to reshape tensors: -->

In [32]:
y = torch.arange(9)
print(y)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])


In [38]:
# Reshape into 3x3 matrix
x_reshaped = y.view(3, 3)
print(f"view : {x_reshaped}")
y_reshape = y.reshape(3, 3)
print(f"reshape: {y_reshape}")

view : tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])
reshape: tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])


In [51]:
# Flattening and Adding Dimensions
# Flattening: Convert a tensor into a 1D vector.
# Unsqueeze: Add an extra dimension.
# Squeeze: Remove dimensions with size 1.


x = torch.arange(9).view(3, 3)
print(x)
flat = x.view(-1)  # Flattened
unsqueezed = flat.unsqueeze(0)  # Add a dimension
squeezed = unsqueezed.squeeze(0)  # Remove dimension

print(f"flat: {flat}")
print(f"unsqueezed: {unsqueezed}")
print(f"squeezed: {squeezed}")

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])
flat: tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])
unsqueezed: tensor([[0, 1, 2, 3, 4, 5, 6, 7, 8]])
squeezed: tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])


# 5. Advanced Operations
# Broadcasting
<!-- Broadcasting automatically aligns tensor shapes for operations: -->

In [52]:
x1 = torch.rand(5, 5)
x2 = torch.rand(1, 5)

In [53]:
print(x1)
print(x2)

tensor([[0.1881, 0.8591, 0.6338, 0.8968, 0.7084],
        [0.2951, 0.5278, 0.6861, 0.7796, 0.8519],
        [0.9376, 0.8551, 0.4216, 0.6040, 0.0802],
        [0.2573, 0.6842, 0.9115, 0.4479, 0.6866],
        [0.0407, 0.8237, 0.7480, 0.0421, 0.9256]])
tensor([[0.5204, 0.3934, 0.0971, 0.7871, 0.9447]])


In [55]:
# Broadcasting x2 to match x1
result = x1 - x2
print(result)

tensor([[-0.3324,  0.4657,  0.5367,  0.1097, -0.2363],
        [-0.2253,  0.1343,  0.5890, -0.0076, -0.0928],
        [ 0.4172,  0.4617,  0.3246, -0.1831, -0.8645],
        [-0.2631,  0.2908,  0.8144, -0.3393, -0.2581],
        [-0.4797,  0.4302,  0.6509, -0.7451, -0.0191]])


# Device Management: GPU vs CPU
<!-- Use .to(device) to move tensors between CPU and GPU: -->

In [56]:
device = "cuda" if torch.cuda.is_available() else "cpu"
x = torch.tensor([1, 2, 3]).to(device)
print(x.device)  # cuda or cpu

cpu


# Converting Tensors and NumPy Arrays
<!-- Seamlessly switch between PyTorch tensors and NumPy arrays: -->

In [58]:
import numpy as np

# NumPy to Tensor
np_array = np.zeros((3, 3))
tensor = torch.from_numpy(np_array)
# Tensor to NumPy
np_array_back = tensor.numpy()

print(tensor)
print(np_array_back)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float64)
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
